export const ANNIVERSARY_GIFTS = [
  {
    id: "gift-1",
    title: "Custom Acrylic LED Night Light with Song & Photo",
    subtitle: "Turn your favorite couple memory and romantic song into a glowing acrylic night light.",
    category: "Personalized Keepsakes",
    price: 1499,
    originalPrice: 2499,
    rating: 4.9,
    reviewsCount: 328,
    image: "https://images.unsplash.com/photo-1518199266791-5375a83190b7?auto=format&fit=crop&q=80&w=800",
    milestone: "1st Year",
    recipient: "For Couples",
    badge: "Bestseller",
    isPersonalizable: true,
    description: "Laser-etched high quality acrylic display with a sleek wooden LED base. Upload your favorite wedding or couple picture and add your favorite song title with Spotify barcode preview!",
    features: ["Warm LED lighting", "Spotify code scannable", "Custom names & wedding date", "USB Powered"]
  },
  {
    id: "gift-2",
    title: "Customized Star Map - The Night We Met",
    subtitle: "An accurate astronomical map showing the exact position of stars on your special day.",
    category: "Memory & Star Maps",
    price: 1899,
    originalPrice: 2999,
    rating: 5.0,
    reviewsCount: 412,
    image: "https://images.unsplash.com/photo-1506703719100-a0f3a48c0f86?auto=format&fit=crop&q=80&w=800",
    milestone: "1st Year",
    recipient: "For Couples",
    badge: "Most Loved",
    isPersonalizable: true,
    description: "Rendered using real planetarium data for any exact location, date, and time. Features premium matte framing and custom romantic title quote.",
    features: ["Astronomically accurate", "Museum-quality paper", "Sleek wooden frame included", "Custom location coordinates"]
  },
  {
    id: "gift-3",
    title: "His & Hers Matching Stainless Steel Engraved Couple Watches",
    subtitle: "Timeless elegance with personalized initials engraved on the back casing.",
    category: "Jewellery & Watches",
    price: 4999,
    originalPrice: 7999,
    rating: 4.8,
    reviewsCount: 194,
    image: "https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?auto=format&fit=crop&q=80&w=800",
    milestone: "5th Year",
    recipient: "For Couples",
    badge: "Luxury Gift",
    isPersonalizable: true,
    description: "Matching rose-gold & obsidian dark watches packed in a handcrafted wooden gift velvet container.",
    features: ["Japanese Quartz movement", "Water resistant 3ATM", "Back-casing laser engraving", "2 Years Warranty"]
  },
  {
    id: "gift-4",
    title: "Custom Engraved 3D Wooden Heart Photo Frame",
    subtitle: "Handcrafted natural teak wood carved with your couple photo & wedding date.",
    category: "Personalized Keepsakes",
    price: 1299,
    originalPrice: 1999,
    rating: 4.9,
    reviewsCount: 285,
    image: "https://images.unsplash.com/photo-1513519245088-0e12902e5a38?auto=format&fit=crop&q=80&w=800",
    milestone: "5th Year",
    recipient: "For Wife",
    badge: "5th Year Traditional",
    isPersonalizable: true,
    description: "Celebrates the 5th wooden anniversary tradition with solid wood craftsmanship and deep laser photo engraving.",
    features: ["100% Solid Natural Wood", "Laser-carved texture", "Tabletop stand & wall mount", "Eco-friendly varnish"]
  },
  {
    id: "gift-5",
    title: "Luxury Preserved Eternal Rose in Glass Dome",
    subtitle: "Real Ecuadorian rose preserved to stay fresh & vibrant for up to 3+ years.",
    category: "Luxury Baskets & Flowers",
    price: 2499,
    originalPrice: 3899,
    rating: 4.9,
    reviewsCount: 510,
    image: "https://images.unsplash.com/photo-1563241527-3004b7be0ffd?auto=format&fit=crop&q=80&w=800",
    milestone: "10th Year",
    recipient: "For Wife",
    badge: "Eternal Symbol",
    isPersonalizable: false,
    description: "Symbolizes everlasting love just like Beauty & the Beast. Wrapped in warm ambient fairy lights inside a crystal glass dome.",
    features: ["100% Real preserved rose", "Built-in fairytale micro-lights", "Crystal clear glass dome", "Requires zero water or maintenance"]
  },
  {
    id: "gift-6",
    title: "25th Silver Jubilee Engraved Pure Sterling Silver Coin & Pendant",
    subtitle: "Hallmarked 925 sterling silver anniversary souvenir with custom date etching.",
    category: "Jewellery & Watches",
    price: 5999,
    originalPrice: 8999,
    rating: 5.0,
    reviewsCount: 167,
    image: "https://images.unsplash.com/photo-1605100804763-247f67b3557e?auto=format&fit=crop&q=80&w=800",
    milestone: "25th Silver Jubilee",
    recipient: "For Wife",
    badge: "25th Jubilee",
    isPersonalizable: true,
    description: "Mark a quarter century of love with genuine silver hallmarked jewelry and custom initials.",
    features: ["925 Sterling Silver certification", "Gift certificate included", "Anti-tarnish coating", "Premium velvet box"]
  },
  {
    id: "gift-7",
    title: "50th Golden Jubilee Keepsake Clock & Memories Scrapbook",
    subtitle: "Gold-plated desk clock accompanied by a leather-bound 50-year memory journal.",
    category: "Personalized Keepsakes",
    price: 6499,
    originalPrice: 9999,
    rating: 5.0,
    reviewsCount: 94,
    image: "https://images.unsplash.com/photo-1544816155-12df9643f363?auto=format&fit=crop&q=80&w=800",
    milestone: "50th Golden Jubilee",
    recipient: "For Couples",
    badge: "Golden Milestone",
    isPersonalizable: true,
    description: "Celebrate 50 glorious years together! Includes a 24k gold-rimmed analog desk clock and a handcrafted leather album with 50 prompt pages.",
    features: ["24K Gold Plated detail", "Handbound leather album", "Includes photo corners & metallic pens", "Velvet display case"]
  },
  {
    id: "gift-8",
    title: "Romantic Starlight Candlelight Picnic & Spa Box",
    subtitle: "Everything needed for an unforgettable candlelit date night at home.",
    category: "Romantic Experiences",
    price: 3299,
    originalPrice: 4999,
    rating: 4.8,
    reviewsCount: 215,
    image: "https://images.unsplash.com/photo-1527529482837-4698179dc6ce?auto=format&fit=crop&q=80&w=800",
    milestone: "All / Custom Year",
    recipient: "For Couples",
    badge: "Date Night Essential",
    isPersonalizable: false,
    description: "Includes scented soy candles, rose petals, essential bath oils, artisanal dark chocolates, matching wine flutes, and romantic playlist cards.",
    features: ["Organic lavender bath bombs", "Hand-poured soy candle", "Artisanal dark chocolate box", "Curated romantic spotify playlist"]
  },
  {
    id: "gift-9",
    title: "Personalized Leather Couple Passport Covers & Luggage Tags",
    subtitle: "Matching full-grain leather travel set for romantic anniversary getaways.",
    category: "Personalized Keepsakes",
    price: 1799,
    originalPrice: 2799,
    rating: 4.9,
    reviewsCount: 340,
    image: "https://images.unsplash.com/photo-1544816155-12df9643f363?auto=format&fit=crop&q=80&w=800",
    milestone: "1st Year",
    recipient: "For Husband",
    badge: "Travel Couple",
    isPersonalizable: true,
    description: "Hand-embossed initials and metal charm accents. Perfect for couple honeymoons and anniversary trips.",
    features: ["Genuine cruelty-free leather", "Custom gold foil stamping", "Includes 2 passport covers & 2 luggage tags", "RFID protective lining"]
  },
  {
    id: "gift-10",
    title: "Personalized Love Timeline Canvas Art (Our Journey)",
    subtitle: "Visualize key milestones: First Date, Proposal, Wedding, & Anniversary dates.",
    category: "Memory & Star Maps",
    price: 2199,
    originalPrice: 3499,
    rating: 4.9,
    reviewsCount: 460,
    image: "https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?auto=format&fit=crop&q=80&w=800",
    milestone: "All / Custom Year",
    recipient: "For Couples",
    badge: "Customer Choice",
    isPersonalizable: true,
    description: "Custom timeline showcasing your love story's landmark moments in elegant calligraphy over gallery-wrapped canvas.",
    features: ["Gallery quality canvas", "Waterproof fade-resistant ink", "Pre-installed wall hook", "Custom date icons"]
  }
];

export const MILESTONES = [
  "All",
  "1st Year",
  "5th Year",
  "10th Year",
  "25th Silver Jubilee",
  "50th Golden Jubilee"
];

export const CATEGORIES = [
  "All Categories",
  "Personalized Keepsakes",
  "Jewellery & Watches",
  "Romantic Experiences",
  "Memory & Star Maps",
  "Luxury Baskets & Flowers"
];

export const RECIPIENTS = [
  "All Recipients",
  "For Wife",
  "For Husband",
  "For Couples"
];
